[package]
name = "p2panda"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.78.0"

[dependencies]
anyhow = "1.0.71"
aquadoggo = { git = "https://github.com/p2panda/aquadoggo", rev = "91e25f31ea474f4fa294b4b0ec7b9d496a5dfa6f" }
flutter_rust_bridge = "1.78.0"
p2panda-rs = { git = "https://github.com/p2panda/p2panda", rev = "ae60bf754a60a1daf9c6862e9ae51ee7501b007f" }
tokio = { version = "1.28.2", features = ["macros", "rt", "rt-multi-thread", "sync"] }
