[package]
name = "p2panda"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.1"

[dependencies]
android_logger = "0.13.1"
anyhow = "1.0.75"
aquadoggo = { git = "https://github.com/p2panda/aquadoggo", rev = "4809fab19382629237c109f4074b9b44312d0d12" }
ed25519-dalek = "1.0.1"
flutter_rust_bridge = "1.82.1"
log = "0.4.19"
p2panda-rs = { git = "https://github.com/p2panda/p2panda", rev = "06b2fee74b40c779d85a0ef3b37bab8386b164ca" }
tokio = { version = "1.28.2", features = ["rt", "rt-multi-thread", "sync", "parking_lot"] }
