name: p2panda
repository: https://github.com/p2panda/meli

packages:
  - packages/*

command:
  version:
    hooks:
      preCommit: bash scripts/version.sh

scripts:
  analyze:
    exec: flutter analyze .
    description: Analyze all Dart packages for code errors and warnings.

  format:
    exec: dart format .
    description: Format all Dart packages according to linter settings.

  build:
    run: bash scripts/build.sh
    description: Compile native p2panda library for Android.
