name: p2panda_flutter
description: p2panda FFI bindings for Flutter
version: 0.1.0
repository: https://github.com/p2panda/meli
publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  p2panda:
    path: ../p2panda

dev_dependencies:
  ffi: ^2.0.1
  ffigen: ^6.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
