name: app
description: Meli Bees App for Android
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  camera: ^0.10.5+4
  carousel_slider: ^4.2.1
  convert: ^3.1.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  form_builder_validators: ^9.0.0
  go_router: ^9.0.3
  graphql_flutter: ^5.2.0-beta.5
  image_picker: ^1.0.4
  intl: ^0.18.0
  p2panda: ^0.1.0
  p2panda_flutter: ^0.1.0
  toml: "^0.14.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true

  # Enable code generation for localization
  generate: true
