name: app
description: Meli Bees App for Android
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  convert: ^3.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  go_router: ^9.0.3
  graphql_flutter: ^5.2.0-beta.5
  intl: ^0.18.0
  p2panda: ^0.1.0
  p2panda_flutter: ^0.1.0
  path_provider: ^2.0.15
  toml: "^0.14.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

  # Enable code generation for localization
  generate: true
