name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # AdoptOpenJDK is now Eclipse Temurin
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.x'
    - run: flutter pub get
    - run: flutter build apk
    - uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
